"""
SDP (Session Description Protocol) Validation

Validates WebRTC SDP offers and answers for required security parameters:
- DTLS-SRTP encryption
- ICE credentials with sufficient entropy
- Valid DTLS fingerprints
- No suspicious relay candidates
"""
import re
from typing import Tuple

# Weak ICE passwords to reject
_WEAK_ICE_PASSWORDS = frozenset([
    'abcdefghijklmnopqrstuvwx', 'password', '12345', '1234567890',
])


def _validate_ice_passwords(sdp: str) -> Tuple[bool, str]:
    """Check ICE passwords are present and sufficiently strong."""
    ice_pwd_matches = re.findall(r'a=ice-pwd:(\S+)', sdp)
    if not ice_pwd_matches:
        return False, "Missing ICE password"

    for pwd in ice_pwd_matches:
        if len(pwd) < 22:
            return False, f"ICE password too short ({len(pwd)} chars, minimum 22)"
        if pwd in _WEAK_ICE_PASSWORDS:
            return False, "Weak ICE password detected"

    return True, ""


def _validate_fingerprints(sdp: str) -> Tuple[bool, str]:
    """Check DTLS fingerprints are present and not dummy values."""
    if 'fingerprint:sha-256' not in sdp:
        return False, "Missing DTLS fingerprint"

    fingerprint_matches = re.findall(r'fingerprint:sha-256 ([A-Fa-f0-9:]+)', sdp)
    for fingerprint in fingerprint_matches:
        upper_fp = fingerprint.upper()
        if upper_fp == '00:' * 32 or upper_fp.count('00:') > 20:
            return False, "Invalid DTLS fingerprint (appears to be dummy value)"

    return True, ""


def _validate_encryption(sdp: str) -> Tuple[bool, str]:
    """Check that DTLS-SRTP encryption is specified."""
    if 'UDP/TLS/RTP/SAVPF' not in sdp and 'DTLS/SCTP' not in sdp:
        return False, "Missing required DTLS-SRTP encryption"
    return True, ""


def validate_offer_sdp(sdp: str) -> Tuple[bool, str]:
    """
    Validate an outgoing SDP offer before sending to the Nest API.

    Checks that the offer (generated by aiortc) has proper ICE credentials,
    DTLS fingerprints, and encryption parameters.

    Returns (is_valid, error_message).
    """
    if 'ice-ufrag' not in sdp:
        return False, "Missing ICE ufrag"

    ok, err = _validate_ice_passwords(sdp)
    if not ok:
        return False, err

    ok, err = _validate_fingerprints(sdp)
    if not ok:
        return False, err

    ok, err = _validate_encryption(sdp)
    if not ok:
        return False, err

    return True, ""


def validate_answer_sdp(sdp: str) -> Tuple[bool, str]:
    """
    Validate an incoming SDP answer from the Nest API before using it.

    In addition to the standard checks, also validates:
    - Required session attributes (ice-ufrag, ice-pwd, setup, mid)
    - Relay candidates don't use private IPs (which would be suspicious)

    Returns (is_valid, error_message).
    """
    # Standard checks
    ok, err = _validate_encryption(sdp)
    if not ok:
        return False, err

    ok, err = _validate_fingerprints(sdp)
    if not ok:
        return False, err

    # Required attributes
    required_attrs = ['ice-ufrag', 'ice-pwd', 'setup:', 'mid:']
    for attr in required_attrs:
        if attr not in sdp:
            return False, f"Missing required SDP attribute: {attr}"

    ok, err = _validate_ice_passwords(sdp)
    if not ok:
        return False, err

    # Check relay candidates don't use private IPs
    for line in sdp.split('\n'):
        if line.startswith('a=candidate'):
            parts = line.split()
            if len(parts) > 7 and parts[7] == 'relay':
                ip = parts[4] if len(parts) >= 5 else ""
                if ip.startswith(('10.', '172.16.', '192.168.', '127.')):
                    return False, f"Suspicious relay candidate with private IP: {ip}"

    return True, ""
